//#define MOTOROFF

#define PIN_FRONT_SENSOR A1
#define PIN_ANGLED_SENSOR A0
#define PIN_SPEED_POT A2
#define PIN_KP_POT A4
//#define PIN_KD_POT A4
#define PIN_KI_POT A5
#define PIN_MAIN_SWITCH 3
#define PIN_LEFT_MOTOR 9
#define PIN_RIGHT_MOTOR 10

#define DEBOUNCE 400
